// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hrhnqwuyhotiswryzgqa.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhyaG5xd3V5aG90aXN3cnl6Z3FhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA3NjQzNTMsImV4cCI6MjA2NjM0MDM1M30.kN4N_m0b-zfZ2-WhVxuOocu-DGMU0unt-EXkIMWxlnw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);